<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Dapper.Contrib" />
    <PackageReference Include="dbup-postgresql" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks.Application\BuildingBlocks.Application.csproj" />
  </ItemGroup>

</Project>
